version: '3'
services:
  mf_drawer_backend:
    build: ./mf_drawer/mf_drawer_backend
    ports:
      - "30303:3030"
    volumes:
      - drawer_db_data:/app/dist/database

  mf_drawer_frontend:
    build: ./mf_drawer/mf_drawer_frontend
    ports:
      - "8080:80"
    volumes:
      - ./mf_drawer/mf_drawer_frontend:/app
    depends_on:
      - mf_drawer_backend

  mf_videos_backend:
    build: ./mf_videos/mf_videos_backend
    ports:
      - "3000:3000"
    volumes:
      - videos_db_data:/app/dist/database

  mf_videos_frontend:
    build: ./mf_videos/mf_videos_frontend
    ports:
      - "8082:80"
    volumes:
      - ./mf_videos/mf_videos_frontend:/app
    depends_on:
      - mf_videos_backend

  main_app:
    build: .
    ports:
      - "80:80"

volumes:
  videos_db_data:
  drawer_db_data:
